# Generated by Django 4.2.2 on 2023-06-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_movie_rating_movieorder_movie_orders"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movieorder",
            old_name="order",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("G", "G"),
                    ("PG", "Pg"),
                    ("PG-13", "Pg 13"),
                    ("R", "R"),
                    ("NC-17", "Nc 17"),
                ],
                default="G",
                max_length=20,
            ),
        ),
    ]
